### ISSUE TITLE
Add releases for TWRP recovery

### ISSUE THREAD

**Issue by ReyKoxha** [xingrz/android_device_smartisan_osborn#1]
Hey xingrz,

maybe it would be a good idea to add the latest images for TWRP to the release tab of your repo.
Down below you can find the latest recovery image based on ac7c9573c0771d17c81c087042bc384462ff0746.
[recovery.zip](https://github.com/xingrz/android_device_smartisan_osborn/files/4073148/recovery.zip)

**Comment by xingrz** [comment]
This repo is for my personal use.

You can get a latest TWRP from https://files.xingrz.me
